AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a single S3 bucket and ec2 instance to test a one-click deployment via Cloudformation.

Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketNamePrefix: prod
      BucketNamespace: acme
      BucketName: my-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  TheInstanceInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316

Outputs:
  BucketName:
    Description: Name of the S3 bucket created by this stack
    Value: !Ref TheBucketsBucket

  InstanceName:
    Description: Name of the instance created by this stack
    Value: !Ref TheInstanceInstance