AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a single S3 bucket and ec2 instance to test a one-click deployment via Cloudformation.

Parameters:
  ChaosBucket7779311:
    Type: String
    Default: ChaosBucket7779311

Resources:
  Chaos-Bucket777-9311:
    Type: 'AWS::S3::Bucket'
    Properties:
     AccessControl: Private
     BucketEncryption:
       ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/gpbucketnamespaces.html
      # Psudeoparameter ---> BucketName: !Sub "${BucketBaseName}-${AWS::AccountId}-${AWS::Region}-an"
      ## can't use bucket name and bucket prefix at same time
      ### ensure you use the same name
      BucketNamePrefix: ChaosBucket7779311 # <--- create parameter !Ref BucketBaseName
      BucketNamespace: "account-regional"   # added "account-regional"
      VersioningConfiguration:
       Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
 BucketName:
   Description: Name of the created S3 bucket
   Value: !Ref ChaosBucket7779311