AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a single S3 bucket and ec2 instance to test a one-click deployment via Cloudformation.

Resources:
  # Logical ID using for bucket
  thebucketsbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/gpbucketnamespaces.html
      # BucketName:       
        ## can use pseudo parameter: BucketName: !Sub "amzn-s3-demo-bucket-${AWS::AccountId}-${AWS::Region}-an"
        ### can't use bucket name and bucket prefix at same time
      # Physcial ID for bucket
      BucketNamePrefix: chaos
      # added "account-regional"
      BucketNamespace: "account-regional"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  TheInstanceInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316

Outputs:
  BucketName:
    Description: Name of the S3 bucket created by this stack
    Value: !Ref thebucketsbucket

  InstanceName:
    Description: Name of the instance created by this stack
    Value: !Ref TheInstanceInstance