AWSTemplateFormatVersion: 2010-09-09
Description:

# =======================
#       Start at column 10
# =======================

   
# =======================
#       PARAMETERS
# =======================


# =======================
#        MAPPINGS
# =======================


# =======================
#        RESOURCES
# =======================


    
# =======================
#       OUTPUTS
# =======================